auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listings/<int:listing_id>", views.listing, name="listing"),
    path("listings/create", views.create_listing, name="create_listing"),
    path("listings/<int:listing_id>/close", views.close_listing, name="close_listing"),
    path("listings/<int:listing_id>/bid", views.bid, name="bid"),
    path("listings/<int:listing_id>/watchlist", views.watchlistadd, name="watchlist_add"),
    path("listings/watchlist", views.watchlist, name="watchlist"),
    path("listings/winnings", views.winnings, name="winnings"),
    path("listings/category", views.category, name="category"),
    path("listings/<int:listing_id>/comment", views.comment, name="comment"),

    path("reset", views.reset, name="BULLSHIT"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Listing(models.Model):
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=300)
    starting_bid = models.IntegerField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner")
    winner_id = models.ForeignKey(User, blank=True,null=True, related_name="winner", on_delete=models.CASCADE)
    image_url = models.CharField(max_length=255, blank=True)
    category = models.CharField(max_length=30,blank=True)
    current_bid = models.IntegerField(default=False)

class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    bid = models.FloatField()


class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import User, Listing, Bid, Watchlist, Comment


def index(request):
    listings = Listing.objects.filter(winner_id=None)
    return render(request, "auctions/index.html", {
        "title": "Active Listings",
        "listings":listings,
        "type": request.GET.get("type", False),
        "message": request.GET.get("message", False),
    })


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


def listing(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    comments = Comment.objects.filter(listing=listing)
    bids = Bid.objects.filter(listing=listing_id)
    watchlist = {}
    if request.user != "AnonymousUser":
        user = request.user.id
        watchlist = Watchlist.objects.filter(user=user, listing=listing)
    else:
        watchlist = 0
    

    highest_bid = False
    for bid in bids:
        if bid.bid > highest_bid:
            highest_bid = bid.bid
            
    return render(request, "auctions/listing.html", {
        "listing": listing,
        "highest_bid":highest_bid,
        "type": request.GET.get("type", False),
        "message": request.GET.get("message", False),
        "watchlist":watchlist,
        "comments":comments,
    })

@login_required(login_url="auctions:login")
def close_listing(request, listing_id):
    if request.method == "POST":
        bids = Bid.objects.filter(listing=listing_id)
        listing = Listing.objects.get(id=listing_id)
        highest_bid = False
        try:
            for bid in bids:
                if not highest_bid:
                    highest_bid = bid
                elif bid.bid > highest_bid.bid:
                    highest_bid = bid
            listing.winner_id = highest_bid.user
            listing.save()
            return HttpResponseRedirect(f"{reverse("auctions:listing", kwargs={"listing_id":listing_id})}?type=success&message=Closing listing success.")
        except:
            listing.winner_id = request.user
            listing.save()
            return HttpResponseRedirect(f"{reverse("auctions:listing", kwargs={"listing_id":listing_id})}?type=anounce&message=Listing is closed without winner.")

        # TODO get highest bidder and set as winner_id for listing
    return HttpResponseRedirect(f"{reverse("auctions:listing", kwargs={"listing_id":listing_id})}?type=fail&message=How did you get here.")

@login_required(login_url="auctions:login")
def bid(request,listing_id):
    if request.method == "POST":
        highest_bet = False
        listing = Listing.objects.get(id=listing_id)
        bids = Bid.objects.filter(listing=listing_id)
        bidvalue = request.POST.get("bid")
        for bid in bids:
            if bid.bid > highest_bet:
                highest_bet = bid.bid
        if float(bidvalue) > float(highest_bet):
            highest_bet = bidvalue
            newbid = Bid(user=request.user, listing=listing, bid=highest_bet)
            newbid.save()
            listing.current_bid = bidvalue
            listing.save()
            return HttpResponseRedirect(f"{reverse("auctions:listing", kwargs={"listing_id":listing_id})}?type=success&message=Bid placed successfully")
        else:
            return HttpResponseRedirect(f"{reverse("auctions:listing", kwargs={"listing_id":listing_id})}?type=fail&message=Bid is to low")

@login_required(login_url="auctions:login")  
def watchlistadd(request, listing_id):
    if request.method == "POST":
        listing = Listing.objects.get(id=listing_id)
        user = request.user
        watchlist = Watchlist.objects.filter(user=user, listing=listing)
        try:
            if(len(watchlist) == 1):
                watchlist[0].delete()
                return HttpResponseRedirect(f"{reverse("auctions:listing", kwargs={"listing_id":listing_id})}?type=success&message=listing is removed from your watchlist")
            else:
                newWatchlist = Watchlist(user=user, listing=listing)
                newWatchlist.save()
            return HttpResponseRedirect(f"{reverse("auctions:listing", kwargs={"listing_id":listing_id})}?type=success&message=listing is added to your watchlist")
        except:
            return HttpResponseRedirect(f"{reverse("auctions:listing", kwargs={"listing_id":listing_id})}?type=fail&message=something went wrong")
@login_required(login_url="auctions:login")
def watchlist(request):
    user = request.user
    watchlist_items = Watchlist.objects.filter(user=user)
    listings = []
    for item in watchlist_items:
        if item.listing.winner_id == None:
            listings.append(item.listing)
    return render(request, "auctions/index.html", {
        "title": "Watchlist",
        "listings": listings,
    })

@login_required(login_url="auctions:login")
def winnings(request):
    listings = Listing.objects.filter(winner_id=request.user).exclude(user_id=request.user)

    return render(request, "auctions/index.html",{
        "title": "Winnings",
        "listings": listings,
    })

@login_required(login_url="auctions:login")
def create_listing(request):
    if request.method == "POST":
        user = request.user
        title = request.POST.get("title").capitalize()
        description = request.POST.get("description").capitalize()
        starting_bid = request.POST.get("starting_bid")
        image_url = request.POST.get("image_url")
        category = request.POST.get("category").capitalize()
        try:
            if image_url == "":
                image_url = False
            NewListing = Listing(title=title, description=description, starting_bid=starting_bid, image_url=image_url, category=category, user_id=user)
            NewListing.save()
            return HttpResponseRedirect(f"{reverse("auctions:index")}?type=success&message=New listing added successfully")
        except:
            return HttpResponseRedirect(f"{reverse("auctions:index")}?type=fail&message=oops something went wrong")
    categories = Listing.objects.values("category").distinct()
    return render(request, "auctions/create_listing.html",{
        "categories":categories,
    })

def category(request):
    category = request.GET.get("category", "None").capitalize()
    listings = Listing.objects.filter(category=category)
    return render(request, "auctions/index.html",{
        "title":category,
        "listings":listings,
    })

@login_required(login_url="auctions:login")
def comment(request, listing_id):
    if request.method == "POST":
        user = request.user
        comment = request.POST.get("comment")
        listing = Listing.objects.get(id=listing_id)
        NewComment = Comment(listing=listing, user=user, comment=comment)
        NewComment.save()
        return HttpResponseRedirect(reverse("auctions:listing", kwargs={"listing_id":listing_id}))




@login_required(login_url="auctions:login")
def reset(request):
    listings = Listing.objects.all()

    for listing in listings:
        listing.winner_id = None
        listing.save()
            
    return HttpResponseRedirect(f"{reverse("auctions:index")}?type=anounce&message=closed listings are open again")

auctions/templates/auctions/create_listing.html
{% extends 'auctions/layout.html' %}
{% block body %}
<h2>Create listing</h2>
<div class="center">
    <form action="{% url 'auctions:create_listing' %}" class="create-form" method="post">
        {% csrf_token %}
        <div><label for="title">title</label><input type="text" name="title" id="title"></div>
        <div><label for="description">description</label><textarea name="description" id="description"
                rows="10"></textarea>
        </div>
        <div><label for="starting_bid">starting bid</label><input type="number" name="starting_bid" id="starting_bid">
        </div>
        <div><label for="image_url">image url</label><input type="text" name="image_url" id="image_url"></div>
        <div>
            <label for="category">category:</label>
            <input list="categories" id="category" name="category" autocomplete="off" />
            <datalist id="categories">
                {% for category in categories %}
                <option value="{{category.category}}"></option>
                {% endfor %}
            </datalist>
        </div>
        <button>Add Listing</button>
    </form>
</div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %} {% block body %}
{% load static %}
<h2>{{ title }}</h2>

<div class="listings">
    <ul>
        {% for listing in listings %}
        <a href="{% url 'auctions:listing' listing.id %}">
            <div class="item">
                <div class="image">
                    {% if listing.image_url != "False" %}
                    <img src="{{ listing.image_url }}" alt=" {{ listing.title }}" />
                    {% else %}
                    <img src="{% static 'auctions\images\placeholder.webp' %}" alt="no image" />
                    {% endif %}
                </div>

                <h3>{{ listing.title }}</h3>
                <div class="info">
                    {% if listing.current_bid %}
                    <p><span>price: </span>{{ listing.current_bid }}</p>
                    {% else %}
                    <p><span>price: </span>{{ listing.starting_bid }}</p>
                    {% endif %}
                    <p><span>category: </span>{{ listing.category }}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </ul>
</div>

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<title>{% block title %}Auctions{% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
		integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
	<link href="{% static 'auctions/styles.css' %}" rel="stylesheet" />
</head>

<body>
	<h1>Auctions</h1>
	<div>
		{% if user.is_authenticated %} Signed in as
		<strong>{{ user.username }}</strong>. {% else %} Not signed in.
		{% endif %}
	</div>
	<ul class="nav">
		<li class="nav-item">
			<a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
		</li>
		{% if user.is_authenticated %}
		<li class="nav-item">
			<a class="nav-link" href="{% url 'auctions:create_listing' %}">Create Listing</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="{% url 'auctions:winnings' %}">Winnings</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
		</li>
		{% else %}
		<li class="nav-item">
			<a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
		</li>
		{% endif %}
	</ul>
	<hr />
	{% if message %}
	<div class="message {{ type }}">
		<p>{{ message }}</p>
	</div>
	{% endif %}

	{% block body %} {% endblock %}
</body>

</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %} {% block body %}
{% load static %}
<div class="listing">
	<div class="header left">
		{% if listing.image_url != "False" %}
		<img src="{{ listing.image_url }}" alt=" {{ listing.title }}" />
		{% else %}
		<img src="{% static 'auctions\images\placeholder.webp' %}" alt="no image" />
		{% endif %}
	</div>
	<div class="content right">
		<div class="buttons">
			{% if user.is_authenticated %}
			{% if watchlist %}
			<form action="{% url 'auctions:watchlist_add' listing.id%}" method="post">{% csrf_token %}<button>remove
					from watchlist</button></form>
			{% else %}
			<form action="{% url 'auctions:watchlist_add' listing.id%}" method="post">{% csrf_token %}<button>add to
					watchlist</button></form>
			{% endif %}
			{% if user.id == listing.user_id.id %}
			<form action="{% url 'auctions:close_listing' listing.id%}" method="post">{% csrf_token %}<button>close
					auction</button></form>
			{% endif %}
			{% endif %}
		</div>
		<h1>{{ listing.title }}</h1>
		<p>{{ listing.description }}</p>
	</div>
	<div class="bidding left">
		{% if user.id and user.id != listing.user_id.id %}
		{% if listing.winner_id %}
		<p><span>winner: </span>{{ listing.winner_id }}</p>
		{% else %}
		{% if user.is_authenticated %}
		<form action="{% url 'auctions:bid' listing.id %}" method="post"><label for="bid"></label>
			{% if highest_bid != False %}
			<input type="number" name="bid" id="bid" min="{{ highest_bid }}" value="{{ highest_bid }}">
			{% else %}
			<input type="number" name="bid" id="bid" min="{{ listing.starting_bid }}"
				value="{{ listing.starting_bid }}">
			{% endif %}
			<button>bid!</button>{% csrf_token %}
			{% endif %}
		</form>
		{% endif %}
		{% else %}
		{% if listing.winner_id %}
		<p><span>winner: </span>{{ listing.winner_id }}</p>
		{% else %}
		{% if highest_bid != False %}
		<p><span>highest bid: </span>${{ highest_bid }}</p>
		{% else %}
		<p><span>highest bid: </span>${{ listing.starting_bid }}</p>
		{% endif %}
		{% endif %}
		{% endif %}

		<p><span>category: </span><a href="{% url 'auctions:category' %}?category={{ listing.category}}">{{ listing.category }}</a></p>

	</div>
	<div class="comments right">
		{% for comment in comments %}
		<p><span>{{ comment.user }}: </span>{{ comment.comment }}</p>
		{% endfor %}
		{% if user.is_authenticated %}
		<form action="{% url 'auctions:comment' listing.id %}" method="post">
			{% csrf_token %}
			<div><textarea name="comment" id="comment" placeholder="comment..." cols="50" rows="5"></textarea></div>
			<button>Submit</button>
		</form>
		{% endif %}
	</div>
</div>

{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2>Login</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'auctions:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input autofocus class="form-control" type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Login">
</form>

Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

<h2>Register</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'auctions:register' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <input class="form-control" type="email" name="email" placeholder="Email Address">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Register">
</form>

Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}